const VERIFY_EMAIL_API = "cb0etLwmAoY86AEoqKtv6zQEujVSbNRdk3qUnSo269iJwNVCme"
const EMAILJS_USER_ID = "user_u9lNbTzYz97A1GyOn48Fp"
const EMAILJS_ACCESS_TOKEN = "4bf2afc38da4a8eb616ebb0146af6093"
const EMAILJS_SERVICE_ID = "service_33p26nx"
const EMAILJS_TEMPLATE_ID = "template_1fwh54m"


export {VERIFY_EMAIL_API, EMAILJS_USER_ID, EMAILJS_ACCESS_TOKEN, EMAILJS_SERVICE_ID, EMAILJS_TEMPLATE_ID}